apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jk59sn37q-python
  janus-idp.io/tekton: jk59sn37q-python
  backstage.io/kubernetes-id: jk59sn37q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jk59sn37q-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
